INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 69.65, 5, 16);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 79.95, 7, 2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 83.81, 22,26);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 84.52, 3, 26);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 68.49, 22, 27);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 102.36,9, 19);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 73.50, 12,23);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 57.11, 2, 29);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 107.05,4, 23);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 25.74, 3, 1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 17.94, 9, 8);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 26.51, 12,12);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 27.66, 25,4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 24.97, 24,15);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 20.33, 20,5);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 69.86, 20,25);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 35.75, 5, 8);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 55.26, 9, 17);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 15.83, 2, 5);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 37.69, 2, 11);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 4.37, 12, 6);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 100.96, 8,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 55.33, 18,8);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 112.28,18,9);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 19.30, 20,6);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 38.70, 11,25);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 30.67, 3, 29);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 97.74, 15,22);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 32.76, 15,23);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 67.38, 11,22);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 65.81, 23,8);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 61.64, 3, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 79.72, 10,5);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 91.97, 13,13);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 96.99, 6, 9);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 26.81, 5, 25);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 63.34, 12,16);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 26.44, 5, 25);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 50.35, 12,11);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 106.88,10,23);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 41.44, 12,17);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 43.73, 18,13);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 18.79, 22,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 84.08, 24,28);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 99.35, 2, 4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 25.29, 12,5);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 93.70, 2, 9);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 95.44, 20,14);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 108.48,18,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 22.19, 11,14);