INSERT INTO cidades(nome,uf) VALUES ('São Paulo','SP');
INSERT INTO cidades(nome,uf) VALUES ('Boa Vista','RR');
INSERT INTO cidades(nome,uf) VALUES ('Aracaju','SE');
INSERT INTO cidades(nome,uf) VALUES ('Aparecida de Goiânia','GO');
INSERT INTO cidades(nome,uf) VALUES ('Teresina','PI');
INSERT INTO cidades(nome,uf) VALUES ('Olinda','PE');
INSERT INTO cidades(nome,uf) VALUES ('João Pessoa','PB');
INSERT INTO cidades(nome,uf) VALUES ('Jaboatão dos Guararapes','PE');
INSERT INTO cidades(nome,uf) VALUES ('Ananindeua','PA');
INSERT INTO cidades(nome,uf) VALUES ('Várzea Grande','MT');
INSERT INTO cidades(nome,uf) VALUES ('Colatina','ES');
INSERT INTO cidades(nome,uf) VALUES ('Ariquemes','RO');
INSERT INTO cidades(nome,uf) VALUES ('Porto Alegre','RS');
INSERT INTO cidades(nome,uf) VALUES ('Fortaleza','CE');
INSERT INTO cidades(nome,uf) VALUES ('Cabo Frio','RJ');
INSERT INTO cidades(nome,uf) VALUES ('Cacoal','RO');
INSERT INTO cidades(nome,uf) VALUES ('Maceió','AL');
INSERT INTO cidades(nome,uf) VALUES ('Sarandi','PR');
INSERT INTO cidades(nome,uf) VALUES ('Imperatriz','MA');
INSERT INTO cidades(nome,uf) VALUES ('Aracruz','ES');
INSERT INTO cidades(nome,uf) VALUES ('Ji-Paraná','RO');
INSERT INTO cidades(nome,uf) VALUES ('Maceió','AL');
INSERT INTO cidades(nome,uf) VALUES ('Macapá','AP');
INSERT INTO cidades(nome,uf) VALUES ('Porto Velho','RO');
INSERT INTO cidades(nome,uf) VALUES ('Guarapari','ES');
INSERT INTO cidades(nome,uf) VALUES ('Campo Grande','MS');
INSERT INTO cidades(nome,uf) VALUES ('Porto Velho','RO');
INSERT INTO cidades(nome,uf) VALUES ('Castanhal','PA');
INSERT INTO cidades(nome,uf) VALUES ('Palhoça','SC');
INSERT INTO cidades(nome,uf) VALUES ('Parnaíba','PI');
INSERT INTO cidades(nome,uf) VALUES ('Brasília','DF');
INSERT INTO cidades(nome,uf) VALUES ('Caroebe','RR');
INSERT INTO cidades(nome,uf) VALUES ('Brasília','DF');
INSERT INTO cidades(nome,uf) VALUES ('Maceió','AL');
INSERT INTO cidades(nome,uf) VALUES ('Campo Grande','MS');
INSERT INTO cidades(nome,uf) VALUES ('Paranavaí','PR');
INSERT INTO cidades(nome,uf) VALUES ('Manaus','AM');
INSERT INTO cidades(nome,uf) VALUES ('Betim','MG');
INSERT INTO cidades(nome,uf) VALUES ('Itapetininga','SP');
INSERT INTO cidades(nome,uf) VALUES ('Goiânia','GO');
INSERT INTO cidades(nome,uf) VALUES ('Natal','RN');
INSERT INTO cidades(nome,uf) VALUES ('Santana','AP');
INSERT INTO cidades(nome,uf) VALUES ('Santa Cruz do Sul','RS');
INSERT INTO cidades(nome,uf) VALUES ('São Paulo','SP');
INSERT INTO cidades(nome,uf) VALUES ('João Pessoa','PB');
INSERT INTO cidades(nome,uf) VALUES ('Natal','RN');
INSERT INTO cidades(nome,uf) VALUES ('Belo Horizonte','MG');
INSERT INTO cidades(nome,uf) VALUES ('Brasília','DF');
INSERT INTO cidades(nome,uf) VALUES ('Paragominas','PA');
INSERT INTO cidades(nome,uf) VALUES ('Natal','RN');