INSERT INTO roupas(nome, cor, tamanho, marca, preco_venda, preco_compra, id_categoria) VALUES ('Camiseta Masculina', 'Preto', 'G', 'Nike', 130.00, 90.00, 2);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_venda, preco_compra, id_categoria) VALUES ('Tenis A', 'Vermelho', '42', 'Nike', 180.00, 120.00, 3);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_venda, preco_compra, id_categoria) VALUES ('Camisa V', 'Azul', 'M', 'Gutti', 200.00, 150.00, 1);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_venda, preco_compra, id_categoria) VALUES ('Meia E', 'Preto', '43', 'Nike', 40.00, 25.00, 6);

INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Chapéu X', 'Azul', '40', 'Adidas', 223.30, 13);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Sapatos G', 'Preto', 'GG', 'Nike', 125.06, 15);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Meias K', 'Vermelho', 'P', 'Gucci', 268.00, 8);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Pijama F', 'Laranja', '39', 'Zara', 180.50, 17);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Sandálias V', 'Amarelo', '43', 'H&M', 0.15, 13);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Saia J', 'Rosa', '38', 'Louis', 377.64, 8);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Calça jeans N', 'Verde', '44', 'Uniqlo', 380.45, 10);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Roupão H', 'Cinza', 'G', 'Hermès', 287.08, 13);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Gravata C', 'Branco', 'XG', 'Rolex', 169.26, 16);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Bermuda A', 'Laranja', '42', 'Cartier', 120.44, 15);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Roupas de baixo L', 'Amarelo', 'PP', 'H&M', 74.39, 5);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Camiseta Y', 'Branco', '41', 'Zara', 313.12, 10);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Vestido I', 'Rosa', 'M', 'Nike', 72.91, 15);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Calça O', 'Vermelho', 'PP', 'Gucci', 216.93, 13);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Jaqueta E', 'Preto', '42', 'Uniqlo', 276.86, 15);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Botas M', 'Azul', 'M', 'Hermès', 210.33, 7);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Blusa B', 'Verde', 'P', 'Adidas', 230.39, 14);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Sapatos F', 'Cinza', '39', 'Louis', 290.24, 6);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Vestido X', 'Branco', 'XG', 'Rolex', 121.80, 1);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Sandálias G', 'Amarelo', '40', 'Cartier', 298.89, 5);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Calça jeans J', 'Cinza', '44', 'Zara', 43.84, 15);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Meias H', 'Vermelho', '43', 'Rolex', 173.26, 13);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Roupas de baixo C', 'Rosa', '41', 'Uniqlo', 335.25, 9);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Saia A', 'Azul', 'GG', 'Nike', 201.85, 9);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Gravata Y', 'Laranja', '38', 'Cartier', 290.54, 2);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Roupão I', 'Preto', 'G', 'Hermès', 155.58, 16);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Chapéu B', 'Verde', '38', 'Louis', 372.17, 2);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Pijama K', 'Azul', 'G', 'Gucci', 37.18, 5);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Bermuda E', 'Vermelho', '42', 'H&M', 32.42, 2);
INSERT INTO roupas(nome, cor, tamanho, marca, preco_compra, lucro_porcentagem, id_categoria) VALUES ('Camiseta V', 'Preto', 'GG', 'Adidas', 57.17, 9);