INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 69.65, 5, 4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 79.95, 7, 2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 83.81, 22,4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 84.52, 3, 4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 68.49, 22,3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 102.36,9, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 73.50, 12,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 57.11, 2, 1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 107.05,4, 2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 25.74, 3, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 17.94, 9, 1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 26.51, 12,3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 27.66, 25,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 24.97, 24,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 20.33, 20,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 69.86, 20,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 35.75, 5, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 55.26, 9, 2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 15.83, 2, 4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 37.69, 2, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 4.37, 12, 4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 100.96, 8,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 55.33, 18,3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 112.28,18,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 19.30, 20,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 38.70, 11,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 30.67, 3, 4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 97.74, 15,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 32.76, 15,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 67.38, 11,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 65.81, 23,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 61.64, 3, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 79.72, 10,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 91.97, 13,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 96.99, 6, 2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 26.81, 5, 2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 63.34, 12,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 26.44, 5, 1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 50.35, 12,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 106.88,10,2);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 41.44, 12,4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (4, 43.73, 18,1);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 18.79, 22,3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 84.08, 24,3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (1, 99.35, 2, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 25.29, 12,4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 93.70, 2, 3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (2, 95.44, 20,3);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (3, 108.48,18,4);
INSERT INTO nota_fiscal_roupas(quantidade, valor, id_nota_fiscal, id_roupa) VALUES (5, 22.19, 11,1);